Model ACE_B8_N4_18_0715_lap_1.2_rep, Test RSS
Test run at 2020-08-22 17:37

model file: ../../models/ACE_B8_N4_18_0715_lap_1.2_rep/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 108, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/ACE_B8_N4_18_0715_lap_1.2_rep/model.py'
