Model ACE_B8_N4_18_09_lap_1.2_reg, Test RSS
Test run at 2020-08-21 21:12

model file: ../../models/ACE_B8_N4_18_09_lap_1.2_reg/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 108, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/ACE_B8_N4_18_09_lap_1.2_reg/model.py'
